### PR TITLE
Improves aesthetic of the "Shake" mechanic.

### PR DESCRIPTION
**Pull request by hyprhare**
(Arguably, a fair amount)

### CODE REVIEW

**Comment by hoovercj** [comment]
Thanks for the PR! Would you be able to add a before/after gif which shows the impact this has?

**Comment by hyprhare** [comment]
Sure thing; I really enjoy this extension (and extensions like it)!

What software would you recommend for capturing a `.gif` of a portion of the screen? (I'm sure I can search and find something, but I'm wondering if you have a personal recommendation.)

**Comment by Pitu** [comment]
@hyprhare ShareX if you are on Windows is probably the best tool out there.

**Comment by ppezaris** [comment]
kind of a shame that this PR is left out there dying on the vine...

**Comment by hyprhare** [comment]
This PR is no longer relevant due to VS Code changes that have since broken the shake behavior...
X-Axis shake only applies to elements in the same tab depth...
Y-Axis shake is completely gone...

**Pull request closed without merging**
